#IMPORTANDO ALGUMAS FUNÇÕES ESPECIFICAS PARA ESSE EXERCICIO
#COS PARA MEDIAR O COSSENO RECEBENDO O ANGULO COMO PARAMETRO
#SEN PARA MEDIAR O SENO RECEBENDO O ANGULO COMO PARAMETRO
#TAN PARA MEDIAR O TANGENTE RECEBENDO O ANGULO COMO PARAMETRO
#RADIANS PARA CONVERTER O ANGULO DE GRAUS PARA RADIANOS

from math import cos,sin,tan,radians

#INTEREÇÃO COM O USUÁRIO PEDINDO O ANGULO EM GRAUS
angulo = float(input("Digite um angulo qualquer e tenha seu seno,cosseno e tangente: "))

#CRIANDO UMA NOVA VARIAVEL PARA RECEBER A CONVERSAO DE ANGULO PARA RANDIANOS E ASSIM CONSEGUIR O SEN,COS,TAN
radianos = radians(angulo)

#ATIVANDO AS FUNÇÕES PASSANDO COMO PARAMETRO O VALOR DO RADIANO E ASSIM CONSEGUINDO O VALOR DAS NOSSAS VARIAVEIS
print(f"Seno = {sin(radians(angulo))}")
print(f"Cosseno = {cos(radians(angulo))}")
print(f"Tangente = {tan(radians(angulo))}")