#IMPORTANDO A BLIBIOTECA DE RANDOMIZAÇÃO DE NUMEROS
import random

#NUM IMPORTA A BIBLIOTECA RANDOM E ATIVA A FUNÇÃO RANDOM À VÁRIAVEL QUE RECEBERÁ UM VALOR ENTRE 0 E 1
num = random.random()

print(num)
 
#NUM IMPORTA A BIBLIOTECA RANDOM E ATIVA A FUNÇÃO RANDINT À VÁRIAVEL NUM2 QUE RECEBERÁ UM VALOR ALEATÓRIO ENTRE OS VALORES DEFINIDOS PELO DESENVOLVEDOR
num2 = random.randint(1,10)

print(num2)